# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ferran\Desktop\DataVisualizerGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DataVisualizer(object):
    def setupUi(self, DataVisualizer):
        DataVisualizer.setObjectName(_fromUtf8("DataVisualizer"))
        DataVisualizer.resize(1153, 819)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DataVisualizer.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(DataVisualizer)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 3, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.loading_ProgressBar = QtGui.QProgressBar(self.centralwidget)
        self.loading_ProgressBar.setEnabled(True)
        self.loading_ProgressBar.setMaximumSize(QtCore.QSize(100, 16777215))
        self.loading_ProgressBar.setMaximum(0)
        self.loading_ProgressBar.setProperty("value", -1)
        self.loading_ProgressBar.setTextVisible(False)
        self.loading_ProgressBar.setInvertedAppearance(False)
        self.loading_ProgressBar.setObjectName(_fromUtf8("loading_ProgressBar"))
        self.horizontalLayout_2.addWidget(self.loading_ProgressBar)
        self.timeStep_Slider = QtGui.QSlider(self.centralwidget)
        self.timeStep_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.timeStep_Slider.setObjectName(_fromUtf8("timeStep_Slider"))
        self.horizontalLayout_2.addWidget(self.timeStep_Slider)
        self.prevStep_Button = QtGui.QPushButton(self.centralwidget)
        self.prevStep_Button.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/icon-ios7-arrow-left-128.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevStep_Button.setIcon(icon1)
        self.prevStep_Button.setObjectName(_fromUtf8("prevStep_Button"))
        self.horizontalLayout_2.addWidget(self.prevStep_Button)
        self.nextStep_Button = QtGui.QPushButton(self.centralwidget)
        self.nextStep_Button.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/icon-ios7-arrow-right-128.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextStep_Button.setIcon(icon2)
        self.nextStep_Button.setObjectName(_fromUtf8("nextStep_Button"))
        self.horizontalLayout_2.addWidget(self.nextStep_Button)
        self.timeStep_LineEdit = QtGui.QLineEdit(self.centralwidget)
        self.timeStep_LineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.timeStep_LineEdit.setObjectName(_fromUtf8("timeStep_LineEdit"))
        self.horizontalLayout_2.addWidget(self.timeStep_LineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.folderLocation_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.folderLocation_lineEdit.setObjectName(_fromUtf8("folderLocation_lineEdit"))
        self.horizontalLayout.addWidget(self.folderLocation_lineEdit)
        self.browse_Button = QtGui.QPushButton(self.centralwidget)
        self.browse_Button.setObjectName(_fromUtf8("browse_Button"))
        self.horizontalLayout.addWidget(self.browse_Button)
        self.loadData_Button = QtGui.QPushButton(self.centralwidget)
        self.loadData_Button.setObjectName(_fromUtf8("loadData_Button"))
        self.horizontalLayout.addWidget(self.loadData_Button)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 1, 1, 1, 1)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.plot_Widget = QtGui.QWidget(self.widget)
        self.plot_Widget.setMinimumSize(QtCore.QSize(500, 500))
        self.plot_Widget.setObjectName(_fromUtf8("plot_Widget"))
        self.plotWidget_layout = QtGui.QVBoxLayout(self.plot_Widget)
        self.plotWidget_layout.setObjectName(_fromUtf8("plotWidget_layout"))
        self.horizontalLayout_3.addWidget(self.plot_Widget)
        self.widget_2 = QtGui.QWidget(self.widget)
        self.widget_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.widget_2)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 333))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tabWidget = QtGui.QTabWidget(self.groupBox_3)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.selectedSpecies_listView = QtGui.QListView(self.tab)
        self.selectedSpecies_listView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.selectedSpecies_listView.setObjectName(_fromUtf8("selectedSpecies_listView"))
        self.verticalLayout_5.addWidget(self.selectedSpecies_listView)
        self.line_3 = QtGui.QFrame(self.tab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_5.addWidget(self.line_3)
        self.availableSpeciesFields_radioButton = QtGui.QRadioButton(self.tab)
        self.availableSpeciesFields_radioButton.setChecked(True)
        self.availableSpeciesFields_radioButton.setObjectName(_fromUtf8("availableSpeciesFields_radioButton"))
        self.verticalLayout_5.addWidget(self.availableSpeciesFields_radioButton)
        self.avSpeciesFields_comboBox = QtGui.QComboBox(self.tab)
        self.avSpeciesFields_comboBox.setObjectName(_fromUtf8("avSpeciesFields_comboBox"))
        self.verticalLayout_5.addWidget(self.avSpeciesFields_comboBox)
        self.customSpeciesFields_radioButton = QtGui.QRadioButton(self.tab)
        self.customSpeciesFields_radioButton.setObjectName(_fromUtf8("customSpeciesFields_radioButton"))
        self.verticalLayout_5.addWidget(self.customSpeciesFields_radioButton)
        self.customSpeciesFields_comboBox = QtGui.QComboBox(self.tab)
        self.customSpeciesFields_comboBox.setEnabled(False)
        self.customSpeciesFields_comboBox.setObjectName(_fromUtf8("customSpeciesFields_comboBox"))
        self.verticalLayout_5.addWidget(self.customSpeciesFields_comboBox)
        self.line_4 = QtGui.QFrame(self.tab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_5.addWidget(self.line_4)
        self.selectSpeciesField_Button = QtGui.QPushButton(self.tab)
        self.selectSpeciesField_Button.setObjectName(_fromUtf8("selectSpeciesField_Button"))
        self.verticalLayout_5.addWidget(self.selectSpeciesField_Button, QtCore.Qt.AlignHCenter)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.availableDomainFields_radioButton = QtGui.QRadioButton(self.tab_2)
        self.availableDomainFields_radioButton.setChecked(True)
        self.availableDomainFields_radioButton.setObjectName(_fromUtf8("availableDomainFields_radioButton"))
        self.verticalLayout_2.addWidget(self.availableDomainFields_radioButton)
        self.av2DDomainFields_comboBox = QtGui.QComboBox(self.tab_2)
        self.av2DDomainFields_comboBox.setObjectName(_fromUtf8("av2DDomainFields_comboBox"))
        self.verticalLayout_2.addWidget(self.av2DDomainFields_comboBox, QtCore.Qt.AlignTop)
        self.available1DDomainFields_radioButton = QtGui.QRadioButton(self.tab_2)
        self.available1DDomainFields_radioButton.setObjectName(_fromUtf8("available1DDomainFields_radioButton"))
        self.verticalLayout_2.addWidget(self.available1DDomainFields_radioButton)
        self.av1DDomainFields_comboBox = QtGui.QComboBox(self.tab_2)
        self.av1DDomainFields_comboBox.setEnabled(False)
        self.av1DDomainFields_comboBox.setObjectName(_fromUtf8("av1DDomainFields_comboBox"))
        self.verticalLayout_2.addWidget(self.av1DDomainFields_comboBox)
        self.customDomainFields_radioButton = QtGui.QRadioButton(self.tab_2)
        self.customDomainFields_radioButton.setObjectName(_fromUtf8("customDomainFields_radioButton"))
        self.verticalLayout_2.addWidget(self.customDomainFields_radioButton)
        self.avCustomDomainFields_comboBox = QtGui.QComboBox(self.tab_2)
        self.avCustomDomainFields_comboBox.setEnabled(False)
        self.avCustomDomainFields_comboBox.setObjectName(_fromUtf8("avCustomDomainFields_comboBox"))
        self.verticalLayout_2.addWidget(self.avCustomDomainFields_comboBox)
        self.line_5 = QtGui.QFrame(self.tab_2)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_2.addWidget(self.line_5)
        self.selectDomainField_Button = QtGui.QPushButton(self.tab_2)
        self.selectDomainField_Button.setObjectName(_fromUtf8("selectDomainField_Button"))
        self.verticalLayout_2.addWidget(self.selectDomainField_Button, QtCore.Qt.AlignHCenter)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_6 = QtGui.QLabel(self.tab_6)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_15.addWidget(self.label_6)
        self.rawFieldSpecies_comboBox = QtGui.QComboBox(self.tab_6)
        self.rawFieldSpecies_comboBox.setObjectName(_fromUtf8("rawFieldSpecies_comboBox"))
        self.horizontalLayout_15.addWidget(self.rawFieldSpecies_comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.label_2 = QtGui.QLabel(self.tab_6)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.rawPlotType_radioButton_1 = QtGui.QRadioButton(self.tab_6)
        self.rawPlotType_radioButton_1.setObjectName(_fromUtf8("rawPlotType_radioButton_1"))
        self.horizontalLayout_7.addWidget(self.rawPlotType_radioButton_1)
        self.rawPlotType_radioButton_2 = QtGui.QRadioButton(self.tab_6)
        self.rawPlotType_radioButton_2.setChecked(True)
        self.rawPlotType_radioButton_2.setObjectName(_fromUtf8("rawPlotType_radioButton_2"))
        self.horizontalLayout_7.addWidget(self.rawPlotType_radioButton_2)
        self.rawPlotType_radioButton_3 = QtGui.QRadioButton(self.tab_6)
        self.rawPlotType_radioButton_3.setObjectName(_fromUtf8("rawPlotType_radioButton_3"))
        self.horizontalLayout_7.addWidget(self.rawPlotType_radioButton_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.freeRaw_widget = QtGui.QWidget(self.tab_6)
        self.freeRaw_widget.setObjectName(_fromUtf8("freeRaw_widget"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.freeRaw_widget)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_4 = QtGui.QLabel(self.freeRaw_widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_11.addWidget(self.label_4)
        self.xRaw_comboBox = QtGui.QComboBox(self.freeRaw_widget)
        self.xRaw_comboBox.setObjectName(_fromUtf8("xRaw_comboBox"))
        self.horizontalLayout_11.addWidget(self.xRaw_comboBox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_3 = QtGui.QLabel(self.freeRaw_widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_13.addWidget(self.label_3)
        self.yRaw_comboBox = QtGui.QComboBox(self.freeRaw_widget)
        self.yRaw_comboBox.setObjectName(_fromUtf8("yRaw_comboBox"))
        self.horizontalLayout_13.addWidget(self.yRaw_comboBox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_5 = QtGui.QLabel(self.freeRaw_widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_14.addWidget(self.label_5)
        self.styleRaw_comboBox = QtGui.QComboBox(self.freeRaw_widget)
        self.styleRaw_comboBox.setObjectName(_fromUtf8("styleRaw_comboBox"))
        self.horizontalLayout_14.addWidget(self.styleRaw_comboBox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.selectRawField_Button = QtGui.QPushButton(self.freeRaw_widget)
        self.selectRawField_Button.setObjectName(_fromUtf8("selectRawField_Button"))
        self.verticalLayout_13.addWidget(self.selectRawField_Button)
        self.verticalLayout_4.addWidget(self.freeRaw_widget)
        self.premadeRaw_widget = QtGui.QWidget(self.tab_6)
        self.premadeRaw_widget.setEnabled(True)
        self.premadeRaw_widget.setObjectName(_fromUtf8("premadeRaw_widget"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.premadeRaw_widget)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.premadeRawPlot_comboBox = QtGui.QComboBox(self.premadeRaw_widget)
        self.premadeRawPlot_comboBox.setObjectName(_fromUtf8("premadeRawPlot_comboBox"))
        self.verticalLayout_14.addWidget(self.premadeRawPlot_comboBox)
        self.premadeRawPlot_Button = QtGui.QPushButton(self.premadeRaw_widget)
        self.premadeRawPlot_Button.setObjectName(_fromUtf8("premadeRawPlot_Button"))
        self.verticalLayout_14.addWidget(self.premadeRawPlot_Button)
        self.verticalLayout_4.addWidget(self.premadeRaw_widget)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.tabWidget, QtCore.Qt.AlignTop)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.widget_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.tabWidget_2 = QtGui.QTabWidget(self.groupBox_4)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.fieldsToPlot_listWidget = QtGui.QListWidget(self.tab_3)
        self.fieldsToPlot_listWidget.setObjectName(_fromUtf8("fieldsToPlot_listWidget"))
        self.verticalLayout_9.addWidget(self.fieldsToPlot_listWidget)
        self.plot_pushButton = QtGui.QPushButton(self.tab_3)
        self.plot_pushButton.setObjectName(_fromUtf8("plot_pushButton"))
        self.verticalLayout_9.addWidget(self.plot_pushButton)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.rows_spinBox = QtGui.QSpinBox(self.tab_4)
        self.rows_spinBox.setMinimum(1)
        self.rows_spinBox.setMaximum(10)
        self.rows_spinBox.setProperty("value", 1)
        self.rows_spinBox.setObjectName(_fromUtf8("rows_spinBox"))
        self.horizontalLayout_9.addWidget(self.rows_spinBox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_11 = QtGui.QLabel(self.tab_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_10.addWidget(self.label_11)
        self.columns_spinBox = QtGui.QSpinBox(self.tab_4)
        self.columns_spinBox.setMinimum(1)
        self.columns_spinBox.setMaximum(10)
        self.columns_spinBox.setProperty("value", 1)
        self.columns_spinBox.setObjectName(_fromUtf8("columns_spinBox"))
        self.horizontalLayout_10.addWidget(self.columns_spinBox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_13 = QtGui.QLabel(self.tab_4)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_12.addWidget(self.label_13)
        self.plotPosition_comboBox = QtGui.QComboBox(self.tab_4)
        self.plotPosition_comboBox.setObjectName(_fromUtf8("plotPosition_comboBox"))
        self.horizontalLayout_12.addWidget(self.plotPosition_comboBox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.normalizedUnits_checkBox = QtGui.QCheckBox(self.tab_5)
        self.normalizedUnits_checkBox.setObjectName(_fromUtf8("normalizedUnits_checkBox"))
        self.verticalLayout.addWidget(self.normalizedUnits_checkBox)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_9 = QtGui.QLabel(self.tab_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_6.addWidget(self.label_9)
        self.plasmaDensity_lineEdit = QtGui.QLineEdit(self.tab_5)
        self.plasmaDensity_lineEdit.setEnabled(False)
        self.plasmaDensity_lineEdit.setObjectName(_fromUtf8("plasmaDensity_lineEdit"))
        self.horizontalLayout_6.addWidget(self.plasmaDensity_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.setNormalization_Button = QtGui.QPushButton(self.tab_5)
        self.setNormalization_Button.setEnabled(False)
        self.setNormalization_Button.setObjectName(_fromUtf8("setNormalization_Button"))
        self.verticalLayout.addWidget(self.setNormalization_Button)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.verticalLayout_8.addWidget(self.tabWidget_2)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_2 = QtGui.QGroupBox(self.widget_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.normTime_lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.normTime_lineEdit.setEnabled(False)
        self.normTime_lineEdit.setObjectName(_fromUtf8("normTime_lineEdit"))
        self.horizontalLayout_4.addWidget(self.normTime_lineEdit)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.SITime_lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.SITime_lineEdit.setEnabled(False)
        self.SITime_lineEdit.setObjectName(_fromUtf8("SITime_lineEdit"))
        self.horizontalLayout_4.addWidget(self.SITime_lineEdit)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_3.addWidget(self.widget_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 2, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        DataVisualizer.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(DataVisualizer)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1153, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTools = QtGui.QMenu(self.menuBar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        DataVisualizer.setMenuBar(self.menuBar)
        self.actionOpen_Folder = QtGui.QAction(DataVisualizer)
        self.actionOpen_Folder.setObjectName(_fromUtf8("actionOpen_Folder"))
        self.actionMake_video = QtGui.QAction(DataVisualizer)
        self.actionMake_video.setObjectName(_fromUtf8("actionMake_video"))
        self.actionAbout = QtGui.QAction(DataVisualizer)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionOpen_Folder)
        self.menuTools.addAction(self.actionMake_video)
        self.menuAbout.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(DataVisualizer)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DataVisualizer)

    def retranslateUi(self, DataVisualizer):
        DataVisualizer.setWindowTitle(_translate("DataVisualizer", "VisualPIC", None))
        self.browse_Button.setText(_translate("DataVisualizer", "Browse", None))
        self.loadData_Button.setText(_translate("DataVisualizer", "Load Data", None))
        self.groupBox_3.setTitle(_translate("DataVisualizer", "Select Fields to Plot", None))
        self.label.setText(_translate("DataVisualizer", "Available species", None))
        self.availableSpeciesFields_radioButton.setText(_translate("DataVisualizer", "Available simulation fields", None))
        self.customSpeciesFields_radioButton.setText(_translate("DataVisualizer", "Custom Fields", None))
        self.selectSpeciesField_Button.setText(_translate("DataVisualizer", "Confirm selection", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DataVisualizer", "Species Fields", None))
        self.availableDomainFields_radioButton.setText(_translate("DataVisualizer", "Available simulation fields", None))
        self.available1DDomainFields_radioButton.setText(_translate("DataVisualizer", "1D fields", None))
        self.customDomainFields_radioButton.setText(_translate("DataVisualizer", "Custom fields", None))
        self.selectDomainField_Button.setText(_translate("DataVisualizer", "Confirm Selection", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DataVisualizer", "Domain Fields", None))
        self.label_6.setText(_translate("DataVisualizer", "Species:", None))
        self.label_2.setText(_translate("DataVisualizer", "Plot type:", None))
        self.rawPlotType_radioButton_1.setText(_translate("DataVisualizer", "1D", None))
        self.rawPlotType_radioButton_2.setText(_translate("DataVisualizer", "2D", None))
        self.rawPlotType_radioButton_3.setText(_translate("DataVisualizer", "Premade fullpage plots", None))
        self.label_4.setText(_translate("DataVisualizer", "X axis:", None))
        self.label_3.setText(_translate("DataVisualizer", "Y axis", None))
        self.label_5.setText(_translate("DataVisualizer", "Style:", None))
        self.selectRawField_Button.setText(_translate("DataVisualizer", "Confirm Selection", None))
        self.premadeRawPlot_Button.setText(_translate("DataVisualizer", "Make Plot", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("DataVisualizer", "Raw Data", None))
        self.groupBox_4.setTitle(_translate("DataVisualizer", "Plot Settings", None))
        self.plot_pushButton.setText(_translate("DataVisualizer", "Make Plot", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("DataVisualizer", "Style", None))
        self.label_10.setText(_translate("DataVisualizer", "Number of rows:", None))
        self.label_11.setText(_translate("DataVisualizer", "Number of columns:", None))
        self.label_13.setText(_translate("DataVisualizer", "Plot on position:", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("DataVisualizer", "Multiplot", None))
        self.normalizedUnits_checkBox.setText(_translate("DataVisualizer", "Allow plotting in non-normalized units", None))
        self.label_9.setText(_translate("DataVisualizer", "Plasma density (10<sup>18</sup> cm<sup>-3</sup>)", None))
        self.setNormalization_Button.setText(_translate("DataVisualizer", "Set", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("DataVisualizer", "Normalization", None))
        self.groupBox_2.setTitle(_translate("DataVisualizer", "Time", None))
        self.label_7.setText(_translate("DataVisualizer", "Normalized", None))
        self.label_8.setText(_translate("DataVisualizer", "IS (fs)", None))
        self.menuFile.setTitle(_translate("DataVisualizer", "File", None))
        self.menuTools.setTitle(_translate("DataVisualizer", "Tools", None))
        self.menuAbout.setTitle(_translate("DataVisualizer", "About", None))
        self.actionOpen_Folder.setText(_translate("DataVisualizer", "Open Folder", None))
        self.actionMake_video.setText(_translate("DataVisualizer", "Make video", None))
        self.actionAbout.setText(_translate("DataVisualizer", "About", None))

